import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@Configuration
@ComponentScan({"com.nu"})
public class AppConfig {
/*	@Bean(name = "customerService")
	public CustomerService getCustomerService() {
//		CustomerServiceImpl service = new CustomerServiceImpl(getCustomerRepo());
		CustomerServiceImpl service = new CustomerServiceImpl();
	
//		service.setCustomerRepo(getCustomerRepo());
		return service;
	}*/

/*	@Bean(name = "customerRepo")
	public CustomerRepo getCustomerRepo() {
		return new HibernateCustomerRepoImpl();
	}*/
}
