import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;
import org.springframework.context.support.PropertySourcesPlaceholderConfigurer;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@Configuration
@ComponentScan({ "com.nu" })
@PropertySource("app.properties")
public class AppConfig {

	@Bean
	public static PropertySourcesPlaceholderConfigurer getPropertySourcesPlaceholderConfigurer() {
		return new PropertySourcesPlaceholderConfigurer();
	}

	/*
	 * @Bean(name = "customerService") public CustomerService getCustomerService() {
	 * // CustomerServiceImpl service = new CustomerServiceImpl(getCustomerRepo());
	 * CustomerServiceImpl service = new CustomerServiceImpl();
	 * 
	 * // service.setCustomerRepo(getCustomerRepo()); return service; }
	 */

	/*
	 * @Bean(name = "customerRepo") public CustomerRepo getCustomerRepo() { return
	 * new HibernateCustomerRepoImpl(); }
	 */
}
